apiVersion: v1
kind: Secret
metadata:
  name: erp-common-secret
  namespace: erp-approval
type: Opaque
stringData:
  JWT_SECRET: THIS_IS_A_SAMPLE_JWT_SECRET_KEY_123456
  EMPLOYEE_DB_USERNAME: user
  EMPLOYEE_DB_PASSWORD: password
  EMPLOYEE_ADMIN_EMAIL: admin@example.com
  EMPLOYEE_ADMIN_PASSWORD: password
  APPROVAL_REQUEST_MONGO_USERNAME: user
  APPROVAL_REQUEST_MONGO_PASSWORD: password
