apiVersion: v1
kind: Service
metadata:
  name: approval-processing-service
  namespace: erp-approval
spec:
  selector:
    app: approval-processing-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval-processing-service
  namespace: erp-approval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approval-processing-service
  template:
    metadata:
      labels:
        app: approval-processing-service
    spec:
      containers:
        - name: approval-processing-service
          image: ghcr.io/ilcm96/dku-ce-erp-microservices/approval-processing-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: erp-common-secret
                  key: JWT_SECRET
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: erp-common-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: erp-common-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: erp-common-secret
                  key: RABBITMQ_USERNAME
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: erp-common-secret
                  key: RABBITMQ_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
