name: Build and Push API Gateway Image

on:
  push:
    branches:
      - main
    paths:
      - 'api-gateway/**'
      - '.github/workflows/build-push-api-gateway.yml'

jobs:
  build-and-push-aggregator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_SECRET }}

      - name: Build and push API Gateway Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.aggregator
          push: true
          tags: ghcr.io/ilcm96/dku-ce-erp-microservices/api-gateway:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
