name: Build and Push Employee Service Image

on:
  push:
    branches:
      - main
    paths:
      - 'employee-service/**'
      - '.github/workflows/build-push-employee-service.yml'

jobs:
  build-and-push-employee-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_SECRET }}

      - name: Build and push Employee Service Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: employee-service/Dockerfile
          push: true
          tags: ghcr.io/ilcm96/dku-ce-erp-microservices/employee-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

